# Site settings
title: DataFox Tech Blog
description: "DataFox Tech Blog"


email: "admin@datafox.com"
baseurl: ""
url: "http://eng.datafox.com"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
sass:
  sass_dir: _sass
  style: compressed


# Google Analytics
analytics_id: "UA-72283306-1"


exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .gitignore
  - docker-compose.yml
