# Site settings
title: "DataFox Tech Blog"
description: "Follow how the DataFox engineering team uses data science and machine learning to provide the best data-driven solutions to meet your growth objectives"
version: "2.5.3"

email: "admin@datafox.com"
baseurl: ""
url: "https://eng.datafox.com"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
sass:
  sass_dir: _sass
  style: compressed


# Linkedin
linkedin: "datafox"


# Facebook
facebook:
  meta: true  # true for show Open Graph Meta Tags
  app_id: false  # add here facebook app id


# Twitter
twitter:
  meta: true  # true for show Metadata Twitter
  username: datafoxco  # twitter name without [at]


# Google Analytics
analytics_id: "UA-72283306-8"


# Disqus
#disqus_name: "datafox-engineering-blog"
disqus_name: false

# Tags cloud
tags_cloud: true

# Navigation (2nd level links supported)
nav:
  Tech Blog:
    - { All Categories:      '/categories/#' }
    - { NodeJS:              '/categories/#nodejs' }
    - { Engineering:         '/categories/#engineering' }
    - { Engineering Culture: '/categories/#engineering-culture' }
    - { Archive:             '/archive/' }

  GitHub:
    - { Open Source: 'https://github.com/datafoxco' }

  By Benefit:
    - { Upgrade Your CRM Data:          'https://www.datafox.com/solutions/data-foundations/' }
    - { Prioritize Your Accounts:       'https://www.datafox.com/solutions/prioritize-your-accounts/' }
    - { Find More Best-Fit Accounts:    'https://www.datafox.com/solutions/account-orchestration/' }
    - { Design Data-Driven Territories: 'https://www.datafox.com/solutions/design-data-driven-territories/' }
    - { Eliminate Account Research:     'https://www.datafox.com/customers/sales-reps/' }
    - { Monitor Your Target Companies:  'https://www.datafox.com/product/company-signals/' }
    - { Automate Prospecting Tasks:     'https://www.datafox.com/solutions/workflow-orchestration/' }
    - { Maximize Conference ROI:        'https://www.datafox.com/customers/event-marketing/' }

  For Sales & Marketing:
    - { Sales Operations: 'https://www.datafox.com/customers/sales-operations/' }
    - { Sales Leadership: 'https://www.datafox.com/customers/sales-managers/' }
    - { Marketing:        'https://www.datafox.com/customers/marketing/' }

  For Finance:
    - { Private Equity:     'https://www.datafox.com/customers/private-equity/' }
    - { Investment Banking: 'https://www.datafox.com/customers/investment-banking/' }

  Applications:
    - { Company Intelligence Platform: 'https://www.datafox.com/product/company-intelligence/' }
    - { Account Scoring:            'https://www.datafox.com/product/account-scoring/' }

  CRM Data Management:
    - { Account Data For Accounts: 'https://www.datafox.com/product/account-data-management/' }
    - { Account Data For Leads:    'https://www.datafox.com/product/lead-enrichment/' }

  Data Sets:
    - { Conferences & Award Lists: 'https://www.datafox.com/product/conference-intelligence/' }
    - { Technographics:            'https://www.datafox.com/product/technographics/' }

  Integrations:
    - { Salesforce:  'https://www.datafox.com/integrations/salesforce/' }
    - { Orchestrate: 'https://www.datafox.com/integrations/salesforce/orchestrate/' }
    - { Enrich:      'https://www.datafox.com/integrations/salesforce/enrich/' }
    - { Marketo:     'https://www.datafox.com/integrations/marketo/' }
    - { Slack:       'https://www.datafox.com/integrations/slack/' }
    - { Chrome:      'https://www.datafox.com/integrations/chrome/' }

  APIs:
    - { Overview:      'https://www.datafox.com/integrations/api/' }
    - { Firmographics: 'https://www.datafox.com/integrations/api/company-firmographics/' }
    - { Signals:       'https://www.datafox.com/integrations/api/company-signals/' }
    - { Conferences:   'https://www.datafox.com/integrations/api/conferences/' }

  Pricing:
    - { Overview: 'https://www.datafox.com/product/pricing/' }

  Customers:
    - { Hear From Customers: 'https://www.datafox.com/customers/overview/' }


# CTA links on navbar
nav_cta:
  first:
    title: 'Log In'
    link: 'https://app.datafox.com'
  second:
    title: 'Sign Up'
    link: 'http://www.datafox.com/signup/?utm_medium=webpage&amp;utm_source=eng-blog&amp;utm_content=navbar'


# Footer Navigation (2nd level links supported)
footer:
  Company:
    - '#'
    - { About Us: 'https://www.datafox.com/company/leadership/' }
    - { Press: 'https://www.datafox.com/company/press/' }
    - { Security: 'https://www.datafox.com/company/security/' }
  Connect:
    - '#'
    - { Partners: 'https://www.datafox.com/company/partners/' }
    - { Careers: 'https://www.datafox.com/company/careers/' }
    - { Sales Ops Meetup: 'https://www.meetup.com/Sales-Optimization' }
  WHATâ€™S DIFFERENT:
    - '#'
    - { Intelligent Data: 'https://www.datafox.com/product/intelligent-data/' }
    - { Account Scoring: 'https://www.datafox.com/product/account-scoring/methodology/' }
    - { Signals Data: 'https://www.datafox.com/product/company-signals/' }
  Resources:
    - '#'
    - { Resource Hub: 'https://www.datafox.com/company/resources/' }
    - { Company Blog: 'https://blog.datafox.com' }
    - { Engineering Blog: 'https://eng.datafox.com' }

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .arcconfig
  - .gitignore
  - docker-compose.yml
  - README.md
  - CHANGELOG.md